import React from 'react';
import Head from 'next/head'
import Header from '../components/Header';
import styles from '../styles/Header.module.css';

export default function Home({bs, tech, sports, health, ent}) {

  // const bsArticles = bs.articles;
  // const techArticles = tech.articles;
  // const sportsArticles = sports.articles;
  // const healthArticles = health.articles;
  // const entArticles = ent.articles;

  console.log(bs);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header/>
        </header>

    <main className='main'>
        <div className={styles.hero}>
        <section className={styles.section}>
          <div className={styles.title}>
            <p>Business</p>
          </div>
            <div className={styles.feed}>
                {/* {bsArticles.map((item, index) => (
                  <div key={index} className={styles.article}>
                    <div className={styles.article}>
                    <img onClick={() => window.location.href=item.url} src={item.urlToImage} alt={item.title}/>
                    <div className={styles.articleDetails}>
                        <h4>{item.title}</h4>
                        <p>{item.publishedAt}</p>
                      </div>
                    </div>
                  </div>
                ))} */}
            </div>
            </section>
            <section className={styles.section}>
            <div className={styles.title}>
              <p>Technology</p>
            </div>
              <div className={styles.feed}>
                {/* {techArticles.map((item, index) => (
                  <div key={index} className={styles.article}>
                    <div className={styles.article}>
                    <img onClick={() => window.location.href=item.url} src={item.urlToImage} alt={item.title}/>
                    <div className={styles.articleDetails}>
                        <h4>{item.title}</h4>
                        <p>{item.publishedAt}</p>
                      </div>
                    </div>
                  </div>
                ))} */}
            </div>
            </section>
            <section className={styles.section}>
            <div className={styles.title}>
              <p>Sports</p>
              </div>
              <div className={styles.feed}>
                {/* {sportsArticles.map((item, index) => (
                  <div key={index} className={styles.article}>
                    <div className={styles.article}>
                    <img onClick={() => window.location.href=item.url} src={item.urlToImage} alt={item.title}/>
                    <div className={styles.articleDetails}>
                        <h4>{item.title}</h4>
                        <p>{item.publishedAt}</p>
                      </div>
                    </div>
                  </div>
                ))} */}
            </div>
            </section>
            <section className={styles.section}>
            <div className={styles.title}>
              <p>Health</p>
            </div>
              <div className={styles.feed}>
                {/* {healthArticles.map((item, index) => (
                  <div key={index} className={styles.article}>
                    <div className={styles.article}>
                    <img onClick={() => window.location.href=item.url} src={item.urlToImage} alt={item.title}/>
                    <div className={styles.articleDetails}>
                        <h4>{item.title}</h4>
                        <p>{item.publishedAt}</p>
                      </div>
                    </div>
                  </div>
                ))} */}
            </div>
            </section>
            <section className={styles.section}>
            <div className={styles.title}>
              <p>Entertainment</p>
            </div>
              <div className={styles.feed}>
                {/* {entArticles.map((item, index) => (
                  <div key={index} className={styles.article}>
                    <div className={styles.article}>
                    <img onClick={() => window.location.href=item.url} src={item.urlToImage} alt={item.title}/>
                    <div className={styles.articleDetails}>
                        <h4>{item.title}</h4>
                        <p>{item.publishedAt}</p>
                      </div>
                    </div>
                  </div>
                ))} */}
            </div>
            </section>
        </div>
    </main>

      <footer className='footer'>
        <p>All Rights Reserved NextNewsZZ</p>
      </footer>
    </div>
  )
}



export const getServerSideProps = async pageContext => {

  const [bsRes, techRes, sportsRes, healthRes, entRes] = await Promise.all([
    fetch(
      `https://newsapi.org/v2/everything?q=reactjs&language=en&pageSize=6`,
      {
        headers: {
            Authorization: `${process.env.NEWS_KEY}`
        },
      }
    ),
    fetch(
      `https://newsapi.org/v2/everything?q=vim&language=en&pageSize=6`,
      {
        headers: {
            Authorization: `${process.env.NEWS_KEY}`
        },
      }
    ),
    fetch(
      `https://newsapi.org/v2/everything?q=etherium&language=en&pageSize=6`,
      {
        headers: {
            Authorization: `${process.env.NEWS_KEY}`
        },
      }
    ),
    fetch(
      `https://newsapi.org/v2/everything?q=nextjs&language=en&pageSize=6`,
      {
        headers: {
            Authorization: `${process.env.NEWS_KEY}`
        },
      }
    ),
    fetch(
      `https://newsapi.org/v2/everything?q=blockchain&language=en&pageSize=6`,
      {
        headers: {
            Authorization: `${process.env.NEWS_KEY}`
        },
      }
    ),
  ])
  const [bs, tech, sports, health, ent] = await Promise.all([
    bsRes.json(),
    techRes.json(),
    sportsRes.json(),
    healthRes.json(),
    entRes.json()
  ]);
  
  return{
    props: {
      bs,
      tech,
      sports,
      health,
      ent
    }
  }
}
